apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: <%= name %>
deploy:
  helm:
    releases:
      - name: <%= name %>
        chartPath: .
        valuesFiles:
          - values.yaml
          - values.override.yaml
